# Generated by Django 2.1.3 on 2019-08-31 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='Ingredient',
        ),
    ]
